### PR TITLE
fix(model/userData): taking permission into account in the UserData r…

### LINKED ISSUE #1071: UserData: manage permissions
à faire sur la branche `feat/move-data-in-postgres`

### PR DESCRIPTION
**Pull request by djangoliv**
…equest

closes #1071

### CODE REVIEW

File: model/userData.js [hunk 1]
```diff
@@ -54,11 +54,31 @@ class UserDataModel {
...
+                return true;
+            } else if (data.is_shared) {
+                if (data.shared_users.includes(currentUser.login)) {
+                    return true;
+                } else {
+                    for (const group of currentUser.groups) {
+                        if (data.shared_profiles.includes(group)) {
+                            return true;
+                        }
+                    }
```
Comment (fbessou) [inline model/userData.js:75]: If you want to make it more readable :
```typescript
const isOwner = data.owned_by === currentUser.login
const isSharedWithUser = isShared && ...
const isSharedWithGroup = isShared && new Set(user.groups).intersect(new Set(user.profiles)
return isOwner || isSharedWithUser || isSharedWithUserGroup
```

**Review by viethungnhu — APPROVED** [review]
